server:
  port: 8879
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.201.121.55:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Header=gateway, userService
            #- Path=/User/**
        - id: inventory
          uri: lb://inventoryservice
          predicates:
            - Header=gateway, inventoryService
        - id: otherResourceservice
          uri: lb://otherResourceservice
          predicates:
            - Header=gateway, otherResourceService
        - id: orderservice
          uri: lb://orderservice
          predicates:
            - Header=gateway, orderService
        - id: managerservice
          uri: lb://managerservice
          predicates:
            - Header=gateway, managerService

